// Generated by gencpp from file daho_vision/arrOfxGawang.msg
// DO NOT EDIT!


#ifndef DAHO_VISION_MESSAGE_ARROFXGAWANG_H
#define DAHO_VISION_MESSAGE_ARROFXGAWANG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daho_vision
{
template <class ContainerAllocator>
struct arrOfxGawang_
{
  typedef arrOfxGawang_<ContainerAllocator> Type;

  arrOfxGawang_()
    : xComponent()  {
    }
  arrOfxGawang_(const ContainerAllocator& _alloc)
    : xComponent(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _xComponent_type;
  _xComponent_type xComponent;





  typedef boost::shared_ptr< ::daho_vision::arrOfxGawang_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daho_vision::arrOfxGawang_<ContainerAllocator> const> ConstPtr;

}; // struct arrOfxGawang_

typedef ::daho_vision::arrOfxGawang_<std::allocator<void> > arrOfxGawang;

typedef boost::shared_ptr< ::daho_vision::arrOfxGawang > arrOfxGawangPtr;
typedef boost::shared_ptr< ::daho_vision::arrOfxGawang const> arrOfxGawangConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daho_vision::arrOfxGawang_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daho_vision::arrOfxGawang_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace daho_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'daho_vision': ['/home/jonet/Documents/Project/ros_vision/src/daho_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::arrOfxGawang_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::arrOfxGawang_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::arrOfxGawang_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbd9af7d26d3b4c7d9623e5d36caf99c";
  }

  static const char* value(const ::daho_vision::arrOfxGawang_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbd9af7d26d3b4c7ULL;
  static const uint64_t static_value2 = 0xd9623e5d36caf99cULL;
};

template<class ContainerAllocator>
struct DataType< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daho_vision/arrOfxGawang";
  }

  static const char* value(const ::daho_vision::arrOfxGawang_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] xComponent\n"
;
  }

  static const char* value(const ::daho_vision::arrOfxGawang_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xComponent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arrOfxGawang_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daho_vision::arrOfxGawang_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daho_vision::arrOfxGawang_<ContainerAllocator>& v)
  {
    s << indent << "xComponent[]" << std::endl;
    for (size_t i = 0; i < v.xComponent.size(); ++i)
    {
      s << indent << "  xComponent[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.xComponent[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAHO_VISION_MESSAGE_ARROFXGAWANG_H
