// Generated by gencpp from file daho_vision/ContourPMFRequest.msg
// DO NOT EDIT!


#ifndef DAHO_VISION_MESSAGE_CONTOURPMFREQUEST_H
#define DAHO_VISION_MESSAGE_CONTOURPMFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daho_vision
{
template <class ContainerAllocator>
struct ContourPMFRequest_
{
  typedef ContourPMFRequest_<ContainerAllocator> Type;

  ContourPMFRequest_()
    : idx(0)  {
    }
  ContourPMFRequest_(const ContainerAllocator& _alloc)
    : idx(0)  {
  (void)_alloc;
    }



   typedef int64_t _idx_type;
  _idx_type idx;





  typedef boost::shared_ptr< ::daho_vision::ContourPMFRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daho_vision::ContourPMFRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ContourPMFRequest_

typedef ::daho_vision::ContourPMFRequest_<std::allocator<void> > ContourPMFRequest;

typedef boost::shared_ptr< ::daho_vision::ContourPMFRequest > ContourPMFRequestPtr;
typedef boost::shared_ptr< ::daho_vision::ContourPMFRequest const> ContourPMFRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daho_vision::ContourPMFRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace daho_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'daho_vision': ['/home/jonet/Documents/Project/ros_vision/src/daho_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::ContourPMFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::ContourPMFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::ContourPMFRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e5dd52e90e59616da26a8fe7e0d2d73";
  }

  static const char* value(const ::daho_vision::ContourPMFRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e5dd52e90e59616ULL;
  static const uint64_t static_value2 = 0xda26a8fe7e0d2d73ULL;
};

template<class ContainerAllocator>
struct DataType< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daho_vision/ContourPMFRequest";
  }

  static const char* value(const ::daho_vision::ContourPMFRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 idx\n"
;
  }

  static const char* value(const ::daho_vision::ContourPMFRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContourPMFRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daho_vision::ContourPMFRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daho_vision::ContourPMFRequest_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAHO_VISION_MESSAGE_CONTOURPMFREQUEST_H
