// Generated by gencpp from file daho_vision/ContourPMFResponse.msg
// DO NOT EDIT!


#ifndef DAHO_VISION_MESSAGE_CONTOURPMFRESPONSE_H
#define DAHO_VISION_MESSAGE_CONTOURPMFRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daho_vision
{
template <class ContainerAllocator>
struct ContourPMFResponse_
{
  typedef ContourPMFResponse_<ContainerAllocator> Type;

  ContourPMFResponse_()
    : ratio(0.0)  {
    }
  ContourPMFResponse_(const ContainerAllocator& _alloc)
    : ratio(0.0)  {
  (void)_alloc;
    }



   typedef double _ratio_type;
  _ratio_type ratio;





  typedef boost::shared_ptr< ::daho_vision::ContourPMFResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daho_vision::ContourPMFResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ContourPMFResponse_

typedef ::daho_vision::ContourPMFResponse_<std::allocator<void> > ContourPMFResponse;

typedef boost::shared_ptr< ::daho_vision::ContourPMFResponse > ContourPMFResponsePtr;
typedef boost::shared_ptr< ::daho_vision::ContourPMFResponse const> ContourPMFResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daho_vision::ContourPMFResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace daho_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'daho_vision': ['/home/jonet/Documents/Project/ros_vision/src/daho_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::ContourPMFResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::ContourPMFResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::ContourPMFResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a9814c2e046da76c15f5a76016fa0c1";
  }

  static const char* value(const ::daho_vision::ContourPMFResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a9814c2e046da76ULL;
  static const uint64_t static_value2 = 0xc15f5a76016fa0c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daho_vision/ContourPMFResponse";
  }

  static const char* value(const ::daho_vision::ContourPMFResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ratio\n"
;
  }

  static const char* value(const ::daho_vision::ContourPMFResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ratio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContourPMFResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daho_vision::ContourPMFResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daho_vision::ContourPMFResponse_<ContainerAllocator>& v)
  {
    s << indent << "ratio: ";
    Printer<double>::stream(s, indent + "  ", v.ratio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAHO_VISION_MESSAGE_CONTOURPMFRESPONSE_H
