// Generated by gencpp from file daho_vision/PosisiBola.msg
// DO NOT EDIT!


#ifndef DAHO_VISION_MESSAGE_POSISIBOLA_H
#define DAHO_VISION_MESSAGE_POSISIBOLA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daho_vision
{
template <class ContainerAllocator>
struct PosisiBola_
{
  typedef PosisiBola_<ContainerAllocator> Type;

  PosisiBola_()
    : x(0)
    , y(0)  {
    }
  PosisiBola_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::daho_vision::PosisiBola_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daho_vision::PosisiBola_<ContainerAllocator> const> ConstPtr;

}; // struct PosisiBola_

typedef ::daho_vision::PosisiBola_<std::allocator<void> > PosisiBola;

typedef boost::shared_ptr< ::daho_vision::PosisiBola > PosisiBolaPtr;
typedef boost::shared_ptr< ::daho_vision::PosisiBola const> PosisiBolaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daho_vision::PosisiBola_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daho_vision::PosisiBola_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace daho_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'daho_vision': ['/home/jonet/Documents/Project/ros_vision/src/daho_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::PosisiBola_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daho_vision::PosisiBola_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::PosisiBola_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daho_vision::PosisiBola_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::PosisiBola_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daho_vision::PosisiBola_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daho_vision::PosisiBola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::daho_vision::PosisiBola_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::daho_vision::PosisiBola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daho_vision/PosisiBola";
  }

  static const char* value(const ::daho_vision::PosisiBola_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daho_vision::PosisiBola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
;
  }

  static const char* value(const ::daho_vision::PosisiBola_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daho_vision::PosisiBola_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosisiBola_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daho_vision::PosisiBola_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daho_vision::PosisiBola_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAHO_VISION_MESSAGE_POSISIBOLA_H
